--- #YAML:1.0
name:               WWW-InstaMapper
version:            0.02
abstract:           Perl interface to the InstaMapper.com API
author:
    - Michael Aquilina <aquilina@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    Date::Parse:     0
    DateTime:        0
    JSON:            0
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4

